### ISSUE TITLE
Long most popular headlines not displaying correctly on Firefox

### ISSUE THREAD

**Issue by jennysivapalan** [guardian/frontend#10036]
Long headlines in the Most popular list do not truncate on Firefox (checked on version 39). It behaves correctly on Chrome

![picture 372](https://cloud.githubusercontent.com/assets/944375/9085976/4094dffa-3b79-11e5-9d08-0e9ecf7cf185.png)

**Comment by OliverJAsh** [comment]
This happens because we have a set height for each item in the list, and when text overflows, we "clamp" it using `-webkit-line-clamp: 4`. This isn't available in Firefox, so the options are:

* remove the height and let the items grow/shrink with the headines
* polyfill `-webkit-line-clamp`
* hide any text that overflows, but without the ellipsis. This will also clip any characters that have tails below the baseline, (g, y, q, etc.)
