### ISSUE TITLE
Add timestamp to comments

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10139]
This was an R2 feature missing in NGW, the crosswords community have probably complained about this being missing in the beta version more then any part of the actual crosswords functionality.

Can this be added, are there any blockers to this change? Seems a shame to cause issues to a very loyal and engaged comments community on our page by losing this.

**Comment by ScottPainterGNM** [comment]
@desbo @rich-nguyen @OliverJAsh

**Comment by OliverJAsh** [comment]
There is actually a timestamp, but it's in a different format? Relative rather than absolute?

You can access the absolute timestamp by hovering over to see the title.

My guess would be that some users will prefer relative, some will prefer absolute. Could we use relative timestamps up until the last hour, and then switch to absolute?
