### ISSUE TITLE
crosswords: add next/previous/latest links

### ISSUE THREAD

**Issue by desbo** [guardian/frontend#10206]

**Comment by paperboyo** [comment]
Just a thought. This is super-super-important, because these buttons will appear one day on all content that has a line up... (series, cartoons from the same author etc.). Or all content, period. It would be good to think about it holistically not to have to redesign it later. Super-happy to discuss (although not sure if I can add anything useful...).

**Comment by ScottPainterGNM** [comment]
Agreed with @paperboyo - have added a low prio flag as this is more of a new feature idea rather than an issue with current crossword functionality

**Comment by NathanielBennett** [comment]
Just took a quick look at this - and obviously, I'd need a design. One caveat is that cryptic numbering gets interrupted by prizzes - so for theguardian.com/crosswords/cryptic/26680, there's no 26681. This info doesn't appear to be in the api so we'd need to figure out some logic to do this.

**Comment by ScottPainterGNM** [comment]
Going to close this as not an actual issue but just an idea for the future
