### ISSUE TITLE
Links to 'more' articles on football front broken

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10243]
When you are on a tag page and select the 'More' button, the articles that then appear aren't selectable as links to that piece of content.

Reproduced on Chrome & Safari

**Comment by michaelwmcnamara** [comment]
Selecting one of these stories with debug open gives:

![image](https://cloud.githubusercontent.com/assets/7239344/9438230/36330b10-4a54-11e5-86a5-d413027714e3.png)

**Comment by michaelwmcnamara** [comment]
Effects football front - homepage and other fronts seem to be working ok.

**Comment by NataliaLKB** [comment]
I will investigate this today!

**Comment by ScottPainterGNM** [comment]
Awesome, thanks @NataliaLKB !

**Comment by NataliaLKB** [comment]
**UPDATE**:

As far as I can tell, there is nothing wrong with the data coming through. The issue is that there is clearly an event being triggered which makes an api call and throws an error. Either, the api call is intended, but is being passed the wrong information. Or, and more likely, this event isn't supposed to be triggered at all.

Do note that if you wait for a while after clicking a "show more" article, eventually it does take you to that article. 

Bizzare things:
- Only on the football front
- I can't replicate on mobile (desktop specific issue)


##### If *anyone* has made any football specific changes lately that you think could effect this let me know!

**Comment by NataliaLKB** [comment]
@ScottPainterGNM @michaelwmcnamara This fix has been deployed to CODE now and should be in PROD soon.

Thanks :).

**Comment by ScottPainterGNM** [comment]
Super awesome, thanks for sorting!
