### ISSUE TITLE
Images on cartoon/picture type pages requested at too low a resolution

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#10467]
Hello,

Example URL: http://www.theguardian.com/commentisfree/picture/2015/sep/09/happy-twonyversary-prime-minister

The images on Cartoon/Picture type pages are requested at 700px max while they are shown at 940px wide on widest breakpoint resulting in crappy quality highlighted by Autrialia's picture editors. There are higher res mastercrops available, we just need to add a correct `src` size.

cc/ @JonnyWeeks

Related to https://github.com/guardian/frontend/issues/9482 (and, possibly, more...).

Regards
Mateusz

**Comment by ScottPainterGNM** [comment]
Is this still an issue or sorted by #10751 ??

**Comment by paperboyo** [comment]
Still very much an issue, @ScottPainterGNM.

**Comment by JonnyWeeks** [comment]
Hey Scott, yep as Mateusz says it's still very much an issue on
Conposer Picture/Cartoon pages. And the identical break-point issue still
exists for Composer Liveblogs as well, so the lion's share of our
photography looks pretty bad when viewed on desktop.

Just to clarify, the problems are only visible when you view the site using
a large browser. When you shrink your browser down to tablet size the
responsive nature of the site obviously kicks in and consequently the
photos all look fine at smaller sizes. Moreover the issue seems to
be specific only to images within the body of Composer Liveblog pages and
Composer Picture/Cartoon pages; by that I mean that expanded views are
unaffected, as are Composer Article pages.

Cheers
Jonny


On Tuesday, 13 October 2015, Mateusz <notifications@github.com> wrote:

> Still very much an issue, @ScottPainterGNM
> <https://github.com/ScottPainterGNM>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/10467#issuecomment-147410011>
> .
>


-- 



*Jonny Weeks*
*picture editor, **Guardian Australia*
*email: jonny.weeks@theguardian.com <jonny.weeks@theguardian.com>*
*mobile: +61(0)448018833*
*landline: +61(0)280768545*
*twitter: @WeeksJonny*
*website: **www.theguardian.com/au <http://www.theguardian.com/au>*
*address: **Level 2, 19 Foster St, Sydney, NSW 2010*

• How to supply photos to Guardian Australia <http://tinyurl.com/oqu38ap>
• How to use The Grid (for Australia staff only)
<http://tinyurl.com/nug8uor>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by JonnyWeeks** [comment]
Hey Oliver, should the change you've just made to cartoon/picture pages
have a positive impact on existing cartoon/picture pages? Because i've just
had a quick look at some existing examples and it seems to me that the
original issues still exists.

See below..... Screen Shot 1 shows you a wide browser view of a
cartoon/picture page with evident loss of image quality (if you look around
the banner saying 'you are safe now' and you'll see what i mean); Screen
Shot 2 shows a shrunken browser view with the illustration looking super
crisp. You'll prob need to view them both at 100% to see what i mean, else
otherwise the difference is imperceptible.

ta
jonny


[image: Inline images 1]
[image: Inline images 2]




*Jonny Weeks*
*picture editor, **Guardian Australia*
*email: jonny.weeks@theguardian.com <jonny.weeks@theguardian.com>*
*mobile: +61(0)448018833*
*landline: +61(0)280768545*
*twitter: @WeeksJonny*
*website: **www.theguardian.com/au <http://www.theguardian.com/au>*
*address: **Level 2, 19 Foster St, Sydney, NSW 2010*

• How to supply photos to Guardian Australia <http://tinyurl.com/oqu38ap>
• How to use The Grid (for Australia staff only)
<http://tinyurl.com/nug8uor>





On 13 October 2015 at 21:55, Oliver Joseph Ash <notifications@github.com>
wrote:

> Closed #10467 <https://github.com/guardian/frontend/issues/10467> via
> e11d532
> <https://github.com/guardian/frontend/commit/e11d5322f3f8502dbd1a0d709a1b08152d664021>
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/10467#event-433894151>.
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
Hey @JonnyWeeks, unfortunately your images didn't come through in your email.

The change has been merged but is being released as we speak. Try again in 10 minutes. I will post here once I have confirmed the release is complete.

Before:
![image](https://cloud.githubusercontent.com/assets/921609/10453413/ba8e347c-71a3-11e5-864c-b693dce641af.png)

After:
![image](https://cloud.githubusercontent.com/assets/921609/10453430/d2ee86f2-71a3-11e5-8611-7496929e9f04.png)

This fixes the issue described by @paperboyo where the image served is smaller than the width of the image in the layout. However, this might be more we can do to make images sharper across the site. @paperboyo Could we serve retina images?

**Comment by OliverJAsh** [comment]
The release is complete.

**Comment by paperboyo** [comment]
I can confirm that the original issue is fixed for pages of this type (same issue in liveblogs still pending: https://github.com/guardian/frontend/issues/9482). Great job and thanks, @OliverJAsh!

We already serve `srcset` images in resolution higher than they are shown at but only for a very small minority of images (large cards on fronts). Extending that to more (all?) imagery requires some thinking, testing and optimisations in related areas. Let’s talk tomorrow. Thanks again!

**Comment by JonnyWeeks** [comment]
Perfect! so yeah the picture/cartoon pages now looks good to me. thank you
very much for sorting that.

Oliver, i don't know how to get you directly by email and I've lost you
from gchat, but here are some images for you to see. Further to what i
suggested in my gchat, I'm now pretty convinced that fronts and liveblogs
are both suffering from break-point issues. As I said, it's subtle compard
to the picture/cartoon issue, but it's the same thing. I'm attaching
screnshots of both a liveblog (large and small browser) and a web-front
(large and small browser), so that you can see how images look soft in a
full size browser, but crisp on a shrunken browser. In the liveblog
example, i would say pay attention to the guy's ginger hair and then you'll
see the what i mean. In the fronts example, just look at the plane debris
in the main image and you'll see what i mean.

Hope that helps

cheers
jonny




*Jonny Weeks*
*picture editor, **Guardian Australia*
*email: jonny.weeks@theguardian.com <jonny.weeks@theguardian.com>*
*mobile: +61(0)448018833*
*landline: +61(0)280768545*
*twitter: @WeeksJonny*
*website: **www.theguardian.com/au <http://www.theguardian.com/au>*
*address: **Level 2, 19 Foster St, Sydney, NSW 2010*

• How to supply photos to Guardian Australia <http://tinyurl.com/oqu38ap>
• How to use The Grid (for Australia staff only)
<http://tinyurl.com/nug8uor>





On 13 October 2015 at 22:17, Oliver Joseph Ash <notifications@github.com>
wrote:

> The release is complete.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/10467#issuecomment-147685946>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
@JonnyWeeks Unfortunately your images are not coming through. I think GitHub loses email attachments when responding via email. Can you try responding at https://github.com/guardian/frontend/issues/10467 instead? From there you can just paste images into the text editor.

**Comment by JonnyWeeks** [comment]
hey oliver,

sorry i haven't had chance to login to github and show you those
screengrabs (i'm on my own laptop at the mo and can't remember the
passwords). TBH you probably don't need to see my screengrabs because all
liveblogs are affected by the break-point issue we've talked about, so you
should be able to see it by looking at any example on our site, i.e.

http://www.theguardian.com/australia-news/live/2015/oct/15/malcolm-turnbull-calls-summit-to-counter-violent-extremism-politics-live

The breakpoint issue is only a problem when the liveblog photos are
displayed at their biggest size.

It's worth noting, though, that liveblogs behave somewhat
counterintuitively (for me, at least) when they are re-sized: when you
expand the browser from tablet-size to 13"-laptop-size, the pictures & text
also expand (as you'd expect them to), but if you keep expanding your
browser, the text and pictures will shrink again (which seems odd). I
mention this only because, like i said before, the breakpoint issue is only
visible when the pictures are physically at their biggest – so you may in
fact need to shrink you browser a bit to see the issue.

ta
jonny





*Jonny Weeks*
*picture editor, **Guardian Australia*
*email: jonny.weeks@theguardian.com <jonny.weeks@theguardian.com>*
*mobile: +61(0)448018833*
*landline: +61(0)280768545*
*twitter: @WeeksJonny*
*website: **www.theguardian.com/au <http://www.theguardian.com/au>*
*address: **Level 2, 19 Foster St, Sydney, NSW 2010*

• How to supply photos to Guardian Australia <http://tinyurl.com/oqu38ap>
• How to use The Grid (for Australia staff only)
<http://tinyurl.com/nug8uor>





On 13 October 2015 at 22:30, Jonny Weeks <jonny.weeks@theguardian.com>
wrote:

> Perfect! so yeah the picture/cartoon pages now looks good to me. thank you
> very much for sorting that.
>
> Oliver, i don't know how to get you directly by email and I've lost you
> from gchat, but here are some images for you to see. Further to what i
> suggested in my gchat, I'm now pretty convinced that fronts and liveblogs
> are both suffering from break-point issues. As I said, it's subtle compard
> to the picture/cartoon issue, but it's the same thing. I'm attaching
> screnshots of both a liveblog (large and small browser) and a web-front
> (large and small browser), so that you can see how images look soft in a
> full size browser, but crisp on a shrunken browser. In the liveblog
> example, i would say pay attention to the guy's ginger hair and then you'll
> see the what i mean. In the fronts example, just look at the plane debris
> in the main image and you'll see what i mean.
>
> Hope that helps
>
> cheers
> jonny
>
>
>
>
> *Jonny Weeks*
> *picture editor, **Guardian Australia*
> *email: jonny.weeks@theguardian.com <jonny.weeks@theguardian.com>*
> *mobile: +61(0)448018833 <%2B61%280%29448018833>*
> *landline: +61(0)280768545 <%2B61%280%29280768545>*
> *twitter: @WeeksJonny*
> *website: **www.theguardian.com/au <http://www.theguardian.com/au>*
> *address: **Level 2, 19 Foster St, Sydney, NSW 2010*
>
> • How to supply photos to Guardian Australia <http://tinyurl.com/oqu38ap>
> • How to use The Grid (for Australia staff only)
> <http://tinyurl.com/nug8uor>
>
>
>
>
>
> On 13 October 2015 at 22:17, Oliver Joseph Ash <notifications@github.com>
> wrote:
>
>> The release is complete.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/guardian/frontend/issues/10467#issuecomment-147685946>
>> .
>>
>
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
