### ISSUE TITLE
Match pages 404-ing

### ISSUE THREAD

**Issue by mr-mr** [guardian/frontend#10538]
When visiting from football/fixtures, several matches are 404-ing on the web.

For example:
http://www.theguardian.com/football/match/2015/sep/16//sport/aa-gent-v-lyon

Apps are loading the match so it doesn't look like a PA issue

**Comment by jennysivapalan** [comment]
@mr-mr I've had a look and I haven't seen any instances of matches 404-ing from http://www.theguardian.com/football/fixtures 

In the example you gave, the match has [past](http://www.theguardian.com/football/2015/sep/16/gent-lyon-champions-league-match-report) and we direct to the match report which pulls in the stats fine. If you have any other examples please let me know otherwise I'll close this later today.

**Comment by ScottPainterGNM** [comment]
As per Jenny's comment, closed off until a new example can be found.

**Comment by jennysivapalan** [comment]
I just found an example! The top fixture (Astana vs Galatasaray) is responding with a 404. The other matches on the fixtures page for the same competition are not. Looks like the redirect http://www.theguardian.com/football/match-redirect/3866766 goes to http://www.theguardian.com/football/match/2015/sep/30//sport/astana-fc-v-galatasaray which 404s. I'm going to take a look now as I suspect once the game is played it will start working.
