### ISSUE TITLE
When video re-watched majority of tracking events aren't fired

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#10895]
Raised by Yannick via email:

We discovered a new video tracking issue:
- if you watch a video, several video tracking events are fired such as video starts (event17)
- if you watch a video until the end and start the video again, none of these video events are fired. The only exception is 'video time viewed' (event57)

**Comment by ScottPainterGNM** [comment]
Retested this and still valid, none of the incremental tracking beacons fire upon re-watching the video. Adding to the video bugs board.

**Comment by ScottPainterGNM** [comment]
Also with Ophan, the same issue. We register a click on the play button again but duration tracking does not happen.

**Comment by SiAdcock** [comment]
This appears to be happening because [`lib/defer-to-analytics`](https://github.com/guardian/frontend/blob/master/static/src/javascripts/lib/defer-to-analytics.js) is being loaded after the [`analytics:ready`](https://github.com/guardian/frontend/blob/master/static/src/javascripts/projects/common/modules/analytics/interaction-tracking.js#L99) event has been fired by `analytics/interaction-tracking`. In this scenario, the `deferToAnalytics()` callback in [`enhanced/media-player`](https://github.com/guardian/frontend/blob/master/static/src/javascripts/bootstraps/enhanced/media-player.js#L194-L201) is never called and Ophan tracking is never initialised.

Why is this suddenly interesting? We are considering the impact of removing VideoJS; progress tracking of old (non-YouTube) video elements has been identified as a potentially important feature. If this feature has been broken for 2.5 years, maybe it's safe to drop it?

c/c @stephanfowler

**Comment by SiAdcock** [comment]
The issue I mention above will be fixed in #19669. After this is merged, we can see whether the re-watching event issue is fixed also.

**Comment by ScottPainterGNM** [comment]
@SiAdcock I'm afraid I just have no idea anymore, they might be GA ones but this far too long for my memory to reach alas.

**Comment by ScottPainterGNM** [comment]
They might even be Omniture ones.....

Might be worth closing this on that basis?
