### ISSUE TITLE
iPhone 6 sticky nav appears + glitches

### ISSUE THREAD

**Issue by Jholder112233** [guardian/frontend#10912]
It only appears intermittently on subsequent page reloads.

Stage 1, loads with a load of white space:
![screen shot 2015-10-20 at 11 27 25](https://cloud.githubusercontent.com/assets/2236852/10604650/af5503fe-771d-11e5-82b8-f3e01d05fd2b.png)

Stage 2, as you scroll the nav flies off:
![img_0218](https://cloud.githubusercontent.com/assets/2236852/10604605/55f8dec0-771d-11e5-9b78-1be6f305c22b.PNG)

Stage 3, the slim nav slides in:
![screen shot 2015-10-20 at 11 27 33](https://cloud.githubusercontent.com/assets/2236852/10604657/b96843ba-771d-11e5-954a-e5eea77eab30.png)

**Comment by ScottPainterGNM** [comment]
@uplne @Calanthe this looks like a takeover slot? Do you know if there was one running when this issue was raised?

**Comment by Jholder112233** [comment]
Getting this still occasionally. Captured a video to show it more clearly. This feels urgent to me. 

https://www.youtube.com/watch?v=zkP1jAVqXic&feature=youtu.be

**Comment by ScottPainterGNM** [comment]
Agreed, I thought it was off on mobile still due to these sorts of bugs?

Banner are on mobile only appear when there's a responsive takeover so
might explain a blank space it the sticky nav is trying to work again?
On Thu, 26 Nov 2015 at 09:00, Josh Holder <notifications@github.com> wrote:

> Getting this still occasionally. Captured a video to show it more clearly.
> This feels urgent to me.
>
> https://www.youtube.com/watch?v=zkP1jAVqXic&feature=youtu.be
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/10912#issuecomment-159851818>
> .
>

-- 

------------------------------
This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by OliverJAsh** [comment]
Can't reproduce on an iPhone 6S, iOS 9. How often are you getting this?

This is a good example of why we need to be able to capture page state, for easier reproduction of bugs.

**Comment by OliverJAsh** [comment]
[In the code, it looks like we don't run the sticky nav at all if the breakpoint is mobile](https://github.com/guardian/frontend/blob/985326aba6565bb955ef2001441e5b83cdffc6e7/static/src/javascripts/projects/common/modules/navigation/sticky.js#L33), so I'm not sure how these responsive takeover ads work? It would be good to get an example of one. /cc @kenlim @ScottPainterGNM 

So, somehow, `breakpoint === 'mobile'` is returning false.

**Comment by sndrs** [comment]
can confirm i experienced this over christmas, but cannot for the life of me recreate it now...
