### ISSUE TITLE
Liveblog's blocks datestamps render incorrectly

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#12102]
Hello,

URL: http://www.theguardian.com/technology/blog/2012/sep/12/iphone-5-launch-apple-live-coverage
On multiple browsers, the date stamps run into the adjacent text like so:

![old-blogs](https://cloud.githubusercontent.com/assets/6032869/13353499/b76f15b4-dc8c-11e5-8343-b0493f3afb2d.png)

Not that the timestamps render absolutely correctly on the newer liveblogs (URL: http://www.theguardian.com/politics/live/2016/feb/18/david-cameron-heads-for-summit-amid-widening-eu-rifts-live-updates):

![new-liveblogs](https://cloud.githubusercontent.com/assets/6032869/13353544/0cc76fca-dc8d-11e5-801e-edc3638b3449.png)

Also, related to not-really-closed https://github.com/guardian/frontend/issues/8482 (URL: http://www.theguardian.com/football/live/2015/mar/03/aston-villa-west-bromwich-albion-live?page=with:block-54f61374e4b0114b1f3c5c89#block-54f61374e4b0114b1f3c5c89 as the old block-URL from the issue stopped working :).

Regards
Mateusz

**Comment by johnduffell** [comment]
that's a known limitation of old liveblogs without "live" in the url, we don't know that they're liveblogs when we fetch from CAPI so we can't get the blocks so we end up with a lump of html we can't format correctly.
Once we start using the blocks instead of the body for articles, this problem will go away
