### ISSUE TITLE
Sport Liveblogs - timestamp overlaps with block headline

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#12558]
Timestamp overlaps with block headline
examples:
http://www.theguardian.com/football/live/2016/mar/26/germany-v-england-international-friendly-live
![image](https://cloud.githubusercontent.com/assets/7239344/14524333/bd8559ea-022f-11e6-91f0-f9e9514cf59b.png)

http://www.theguardian.com/football/2014/apr/18/football-league-clockwatch-live-mbm
![image](https://cloud.githubusercontent.com/assets/7239344/14524323/b1dddf68-022f-11e6-8549-70ca18dd88d9.png)

On non-sport liveblogs there is some padding that separates the timestamp and block contents.
This appears to be missing in sport liveblogs.

**Comment by paperboyo** [comment]
Eeee, I would say all liveblogs are broken. Although to a different extent :smile:

Duplicate: https://github.com/guardian/frontend/issues/12102

**Comment by johnduffell** [comment]
we could make the space bigger, but given that most liveblog traffic is to current liveblogs, it makes sense to optimise for that case.  The second formatting issue is known and will go away once we start fetching blocks instead of body from CAPI for everything.  It only affects liveblogs without live in the url, which are all old.
