### ISSUE TITLE
Branding overlay is cropped in WhatsApp and Facebook Messenger

### ISSUE THREAD

**Issue by TormodMacLean** [guardian/frontend#13340]
When an image is shared via whatsApp or Facebook Messenger the image is cropped as a square. This means the new branding overlay is cropped so only "theg" appears instead of "theguardian".
1. Share any guardian content with an image via WhatsApp or Facebook Messenger.
2. Observe that the branding overlay is cropped so as to be unreadable.

![img_0504](https://cloud.githubusercontent.com/assets/11612847/16192691/abeba9d6-36e2-11e6-9ccb-bde176e2b3cf.png)

![img_0505](https://cloud.githubusercontent.com/assets/11612847/16192693/aee5498a-36e2-11e6-97ef-38b8effda236.png)

It is expect that the branding will be readable.
- Device: iPhone 6s
- Browser (inc version): N/A
- OS: iOS 9.3.2

@katebee

**Comment by katebee** [comment]
The hope was that we could provide different image crops for different contexts.

Placing multiple OG image tags does allows users to choose between images when sharing to their timeline, however, we have found that WhatsApp and Facebook Messenger seem to always take the larger image when links are shared, then apply a square crop.

for example:

```
    <meta property="og:image" content="squareimage.jpg"/>
    <meta property="og:image:width" content="400" />
    <meta property="og:image:height" content="400" />

    <meta property="og:image" content="largeimage.jpg"/>
    <meta property="og:image:width" content="1200" />
    <meta property="og:image:height" content="630" />
```

Ideally, using multiple OG image tags on a page would cause the one with the optimal dimensions to be used in the context; using the square image rather than cropping the letterbox one.

## KEY POINTS
- Crawlers **can** scrape multiple og:image tags
- The `og:image:width` and `og:image:height` immediately following the `og:image` will be associated
- We rely on the owners of the crawler to do something with the scraped data
- This is currently outside of our control 

😢

**Comment by michaelwmcnamara** [comment]
@katebee 
Hiya, is there any action still to be done on this, or is this something we can't fix?

**Comment by katebee** [comment]
@michaelwmcnamara nothing we can do at this point 😢

**Comment by ScottPainterGNM** [comment]
@katebee I don't suppose it's an option to shift the guardian logo to be left aligned on the branding overlay across the board? I guess maybe it's not in line with our design but this may solve these issues as they crop the right in all instances mentioned above?

**Comment by mchv** [comment]
@katebee @ScottPainterGNM I think I know how to fix this and as well the `google` cropped similar issue

<img width="241" alt="screen shot 2017-01-24 at 13 00 56" src="https://cloud.githubusercontent.com/assets/615085/22248172/417a2632-e235-11e6-8488-81a1a44d850a.png">

**Comment by ScottPainterGNM** [comment]
@mchv oooo that would be great, tell me more!

**Comment by mchv** [comment]
If someone is interested to work on this, let me know as I will explain how we could fix this.

**Comment by katebee** [comment]
@mchv 🙌 (sorry, it has been a busy quarter!) 

Could we grab some time tomorrow to talk through?

**Comment by emperyalz** [comment]
Hey @mchv & @katebee did you ever get this worked out?

I have some ideas on Rich Previews Links (OG Image) and how to establish some uniformity on each platforms screen size.

**Comment by AWare** [comment]
Fixing this would require serving different metadata to the crawlers for WhatsApp et al. This work is not currently planned.

**Comment by Aleqsd** [comment]
> @katebee @ScottPainterGNM I think I know how to fix this and as well the `google` cropped similar issue
> 
> <img alt="screen shot 2017-01-24 at 13 00 56" width="241" src="https://cloud.githubusercontent.com/assets/615085/22248172/417a2632-e235-11e6-8488-81a1a44d850a.png">

Hey, still interested by this, would you care to share your solution with me please ? 😁
