### ISSUE TITLE
Site running slow in Uganda

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#15686]
A user has reported the site has been running slow for him for the past week in Uganda

Will add info as it comes

**Comment by gidsg** [comment]
I would recommend getting the user to send over all the details from hitting https://www.fastly-debug.com/ in case there is a fastly issue.

**Comment by SiAdcock** [comment]
Hi @michaelwmcnamara, do you remember receiving any more info regarding this issue?

**Comment by SiAdcock** [comment]
Very likely that this is due to the switchover to HTTPS. 

https://meyerweb.com/eric/thoughts/2018/08/07/securing-sites-made-them-less-accessible/

We're already following the recommendations from this article, so I'm not sure what else we can do. Maybe lobby Fastly to create more [Points of Presence](https://www.fastly.com/network-map) in Africa?

**Comment by SiAdcock** [comment]
I'm closing this issue for now as there's not much we can do to change the nature of HTTPS. The benefits of HTTPS far outweigh the problems it causes for local caching servers.

The experience of those using slow / expensive networks can be improved by:

1. The Guardian reducing page weight, which we are working on as part of the componentisation project
2. Fastly adding a POP closer to the user experiencing the slowness

If anyone can think of any more ways we can improve experience for these users, please come and chat to the Platform team.
