### ISSUE TITLE
Old articles appear in various RSS feeds

### ISSUE THREAD

**Issue by fturco** [guardian/frontend#16601]
There are old articles in various RSS feeds from The Guardian. For example in https://www.theguardian.com/science/rss there is an article that was originally published on March 23, 2015 (more than 2 years ago). Is there a way to avoid displaying old articles?

**Comment by SiAdcock** [comment]
Hi @fturco, thanks for raising. RSS feeds are usually populated based on the content of fronts, which may include containers such as "You may have missed", "Most popular" or "From the archive". These containers often feature older news articles, so this is probably the reason you saw a 2 year old article in your RSS reader.

I've spoken to the team that controls the population of RSS feeds, and they have since excluded containers that are likely to feature older news content. This sort of issue should not be happening in the future.

Many thanks for your report.
