### ISSUE TITLE
Android: Non-breaking hyphens appear as underscores

### ISSUE THREAD

**Issue by hugovk** [guardian/frontend#17506]
# Android: Non-breaking hyphens appear as underscores

## Steps to Reproduce

1. With Android/Chrome, visit an article using a non-breaking hyphen, eg. https://www.theguardian.com/sport/blog/2017/jul/24/why-chris-froome-will-not-win-five-tours-de-france contains "tear‑your‑hair‑out" and "one‑on‑one".

## Actual Results (include screenshots)

Non-breaking hyphens appears as underscores.

---

![screenshot_20170725-101706](https://user-images.githubusercontent.com/1324225/28560976-3f8f9bde-7125-11e7-8db0-1122baa3b22c.jpg)

---

![screenshot_20170725-101740](https://user-images.githubusercontent.com/1324225/28560989-47cf75e4-7125-11e7-8513-c9c5fcd3abf6.jpg)

---

## Expected Results (include screenshots)

Non-breaking hyphens appears as hyphens, not underscores. For example, on desktop (latest Chrome Version 59.0.3071.115 (Official Build) (64-bit), macOS Sierra):

---

![image](https://user-images.githubusercontent.com/1324225/28560631-3191bdb0-7124-11e7-9edf-82e7fc76cfc4.png)

---

![image](https://user-images.githubusercontent.com/1324225/28560655-47545e28-7124-11e7-9005-8112e6f1a60d.png)

---

## URL

https://www.theguardian.com/sport/blog/2017/jul/24/why-chris-froome-will-not-win-five-tours-de-france

## OS and Browser details

- Device: Samsung S8
- Browser (inc version): Chrome 59.0.3071.125 (latest) and Samsung Browser 5.4
- OS: Android Nougat 7.0

---

## Notes

I've noticed this in quite a few articles lately. If I Google it, it shows up fine in Google itself, so this looks like a Guardian font problem:

![screenshot_20170725-102429](https://user-images.githubusercontent.com/1324225/28561050-923335e4-7125-11e7-89fe-f7bd78d9a33f.jpg)

http://unicodelookup.com/#‑/1 says this is a non-breaking hyphen:
```
  | Unicode character   | Oct    | Dec  | Hex    | HTML
‑ | non-breaking hyphen | 020021 | 8209 | 0x2011 | &#8209;
```

*Please add relevant labels*

**Comment by paperboyo** [comment]
Hi, @hugovk, thanks for the reporting!

This looks like a bug in Chrome for Android when it comes to finding a fallback glyph for a missing U+2011 (this glyph is missing from our fonts currently). Even in desktop version of the browser, fallback is not correct one might argue (although at least it’s not as wrong as to use an underscore!) – browsers should fall back to a hyphen glyph from the same font instead of using a whole other fallback font.

I vaguely remember Microsoft browsers being smarter about it, but can’t double check now.

We intend to include this glyph in the new version of our fonts to workaround all these browsers’s quirks, but we do not have an ETA for that, unfortunately.

**Comment by paperboyo** [comment]
I spoke too soon (my usual trait). Firefox for Android displays U+2011 correctly as it contains its own set of (fallback) fonts.

Chrome for Android, encountering a missing U+2011, goes by the fallback specified in `/system/etc/fonts.xml` (API 21+) or `system/etc/system_fonts.xml` (API 16-20). According to family definitions there (Galaxy S7 tested here), missing Georgia from our CSS `font-family` falls back to `serif`. `serif` is specified to be NotoSerif[weight].ttf.

Extremely surprisingly, a no tofu (!) NotoSerif-Regular.ttf is missing U+2011 glyph as well! So the next fallback is NotoNaskhArabic-Regular.ttf. This is the first font that does contain a non-breaking hyphen at U+2011. Unfortunately, it doesn’t look correctly placed within a Latin script context (even after https://github.com/googlei18n/noto-fonts/issues/858#issuecomment-290193725).

In my humblest of opinions, browsers should use a hyphen glyph from the same font to render a missing non-breaking hyphen glyph (similarly, e.g. a width of a non-breaking space could be wrong in fallbacks) instead of using fallback fonts.

And Latin flavours of Noto fonts should contain U+2011 glyph.

And Microsoft browsers aren’t really more clever, as I suggested above – just the fallback on Win10 matches our font a bit better.

And we will workaround it by deploying new fonts. I wonder who will be first 😆.

**Comment by turkeyphant** [comment]
This has been going on for months now and is extremely distracting to read. I don't know what renderer the Guardian app uses, but it's worth mentioning the bug persists there too.

**Comment by mchv** [comment]
@turkeyphant android app is now fixed (_version 6.8_)

**Comment by turkeyphant** [comment]
Thank you! It's been aaaaages. I'll update and check today.

**Comment by turkeyphant** [comment]
Weird, still have the issue in Chrome but not in app.

**Comment by SiAdcock** [comment]
@turkeyphant @hugovk This is now fixed on the web too. Thanks very much for reporting.

**Comment by hugovk** [comment]
Confirmed:

![20181010_130304](https://user-images.githubusercontent.com/1324225/46729112-16d03900-cc8d-11e8-87b1-0fae5e3599c4.jpg)

Thank you for your investigation and persistence in solving this!
