### ISSUE TITLE
Frontend DevX - DCR does not hydrate when rendered through frontend

### ISSUE THREAD

**Issue by OllysCoding** [guardian/frontend#24874]
From chat: 

Hi! when we run frontend dev-build and test a url like this `http://localhost:9000/<id of the article>` None of the hydration seems to be working. and we get 500 for all of the scripts (including island). Do you know what I'm doing wrong here?

![image](https://user-images.githubusercontent.com/9575458/162407144-46db385c-f443-4e12-899b-8f7416e536c6.png)

**Comment by jlieb10** [comment]
I think if you're running frontend locally, you also need to be running DCR locally for certain parts of the site to work - is it possible this is the issue?

**Comment by OllysCoding** [comment]
No in this case Frontend & DCR are running locally - the Article renders on DCR, but when the page loads, the script assets it tries to fetch get a 500 error from Frontend

**Comment by chrislomaxjones** [comment]
This may only be tangentially related but I think a similar problem, where an asset path relative to the DCR dev server is passed to Frontend. It was fixed in [DCR #3471](https://github.com/guardian/dotcom-rendering/pull/3471), although it looks like this fix is no longer present. I'm not sure if this would produce similar errors for scripts like `islands.js`.

**Comment by liamness** [comment]
Seems it's possible to bypass this issue by using `m.thegulocal.com` and `dcr?=false`. Conversely, if you need to test DCR, using `localhost:3030` works for me.
