### ISSUE TITLE
Improve error messaging on Preview server to be more descriptive

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#8488]
Steps to reproduce
==============
Go to a 404 on Preview server:
http://preview.gutools.co.uk/404

Actual Results
============
![screen shot 2015-03-04 at 15 27 10](https://cloud.githubusercontent.com/assets/1764158/6486446/f74d3488-c282-11e4-94fd-9d70bf9b1c9a.png)
Response code: `500`

Expected Results
==============
More descriptive error that shows this is really a 404 coming back from CAPI?

-------

*This non-descriptive error message is confusing production people who tend to think 'Preview is broken' rather than 'the path has changed'*

CC @janua

**Comment by johnduffell** [comment]
this issue hasn't been fixed yet and probably won't be in the near future so closing for now

**Comment by janua** [comment]
This one is a bit tricky; because `play` is running in `production` mode, it by default suppresses these errors. If we switched on `errors` in preview we would get an even more scary looking `stacktrace`.

To get a meaningful error, we would have to catch the specific errors that happen during path changes and show an meaningful output for that. This would include changing the controller that is used by both `facia` and `preview`, whilst keeping the functionality `router` has for `facia` and changing it for `preview`. (If you understand the whole stack you'll know what I mean, I think).

Maybe a `stacktrace` is good enough? Probably not.

**Comment by johnduffell** [comment]
stack trace is better than nothing if it's easy enough
