### ISSUE TITLE
Macbook with zoom at 90% does not display borders for text boxed

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#8507]
Macbook with 90% zoom does not display borders for text boxes
Ken also found this at 100% zoom on his computer owning to some custom font settings he had set.

![image](https://cloud.githubusercontent.com/assets/7239344/6509356/b5c1fbd2-c356-11e4-94bd-85220bb5c65a.png)

**Comment by johnduffell** [comment]
this issue hasn't been fixed yet and probably won't be in the near future so closing for now

**Comment by davidrapson** [comment]
@michaelwmcnamara  @johnduffell  Even though this is now closed FWIW I can provide some more context on this one.

It's due to all `px` values being converted to [rems](https://developer.mozilla.org/en/docs/Web/CSS/length#rem).  As rem is a relative value  when you zoom out some previously 1px borders get calculated as sub-1px.

Some browsers (only been able to repeat in Webkit-based browsers) treat any border-widths that calculate to less than  <1px as 0. Depends on the browsers rounding rules I guess.  Border-widths are slightly odd when it comes to non px length values so it doesn't surprise me there's some weirdness.

Result is that all 1px borders disappear when you zoom out.

Still probably not critical enough to worry about, but it is more than text-boxes.
