### ISSUE TITLE
Facebook autosignin message masked by breaking news.

### ISSUE THREAD

**Issue by tudorraul** [guardian/frontend#8600]
We display a message upon autosingin in a user using Facebook. This can be unexpected, so we enforce communicating it to the user by displaying a message.
With the introduction of breaking news, this is no longer obvious, since it overlaps the message.
I think this needs to be rethought. 

FB autosignin happens when: 
1/ you're logged into FB
2/ you've previously accepted our FB app permissions (ie after a successful FB login)
3/ make sure cookies are whipped
4/ you land on a frontend page (and you're not already signed in -- ensured by 3/)

### After FB autosignin
![screen shot 2015-03-16 at 14 13 13](https://cloud.githubusercontent.com/assets/1492162/6667851/b8093a98-cbe6-11e4-9b1d-13ca08388226.png)

### After closing breaking news message
![screen shot 2015-03-16 at 14 13 20](https://cloud.githubusercontent.com/assets/1492162/6667858/bdd3b70a-cbe6-11e4-8138-2b553f351c57.png)

**Comment by ScottPainterGNM** [comment]
Is this issue still occuring? I'm having issues with getting automatically signed in when clicking through from facebook.

**Comment by johnduffell** [comment]
this hasn't been fixed so far so it's not likely to be fixed any time soon

**Comment by markjamesbutler** [comment]
@johnduffell Can I ask why?

**Comment by johnduffell** [comment]
@markjamesbutler  I think both can be covered by the fact that we are too small team and we have bigger issues (e.g. apple devices crashing and performance) that are taking all our time to sort out.  The reason I've closed them now specifically is because we're making sure github issue list is the things we are honestly fixing, rather than an end in its own right.  Then we can start using them for the sustain team.  Unfortunately I have had t close a lot of things are really bugs, but we have to be as realistic as possible.  Feel free to chat me if you want to discuss more.
