### ISSUE TITLE
Galleries appear in their own "More galleries" list

### ISSUE THREAD

**Issue by theefer** [guardian/frontend#8727]
Eg http://www.theguardian.com/artanddesign/gallery/2015/mar/30/fallout-fukushima-pictures-japan-nuclear-tsunami-photographers

**Comment by OliverJAsh** [comment]
I spent some time looking at this. We could dedupe based on the referrer gallery, but it would massively fragment our cache. We decided we would compromise the UX instead.

@phamann If the `/gallery/most-viewed.json` endpoint returned structured data about the galleries instead of HTML, and we thus moved templating to the client-side, it would be a lot easier to workaround this problem. We could dedupe on the client, before rendering. How come we are using server-side templating instead of client-side?

**Comment by phamann** [comment]
@OliverJAsh As one of our line-in-the-sand is to opt for server side templating over client-side wherever possible. I'll talk to you about this in more depth in-person.

**Comment by paperboyo** [comment]
Hi,

Just to note that this is by no means confined to galleries and 'more galleries' list. Sometimes they also appear in 'related content' after appearing in 'more galleries'; rich-links are duplicated in 'related content' as well, galleries are persistently recommended in gallery end slate after watching. And if one is really lucky, all of that is also featured in 'most popular'.

Also, if it's about drones, the exact same picture of a drone is used for all related stories as well ;-D

Regards
Mateusz

**Comment by theefer** [comment]
Lines in the sand move with the tides :-)
