### ISSUE TITLE
Image caption and credit are not in sync with CAPI

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#8833]
Hello,

All platforms. Elaboration on https://github.com/guardian/frontend/issues/8446. Modifications done to Caption and Credit fields and to the Display credit information switch after the content has been launched are not reflected on frontend. They appear in CAPI, though. Initially, I thought it only confined to Picture/Cartoon type, but actually all content is affected.

An example:

http://www.theguardian.com/news/2015/apr/09/kremlin-hall-of-mirrors-military-information-psychology
CAPI:
```
id": "4b2ef7647554fb0f555f996f88c5e62930b0ea4d",
"relation": "main",
"type": "image",
"assets": [
{
"type": "image",
"file": "http://media.guim.co.uk/4b2ef7647554fb0f555f996f88c5e62930b0ea4d/15_600_1903_1142/140.jpg",
"typeData": {
"displayCredit": "true",
"secureFile": "https://media.guim.co.uk/4b2ef7647554fb0f555f996f88c5e62930b0ea4d/15_600_1903_1142/140.jpg",
"source": "Daniel Haskett",
"role": "showcase",
"imageType": "Illustration",
"altText": "Pomerantsev",
"height": "84",
"credit": "Illustration: Daniel Haskett",
"mediaId": "4b2ef7647554fb0f555f996f88c5e62930b0ea4d"
```

More examples: https://github.com/guardian/frontend/issues/8446

In my humble opinion this is quite severe. I can think of instances when the content would have to be taken down entirely...

cc/ @phamann @crifmulholland @na7hangood

Regards
Mateusz

**Comment by michaelwmcnamara** [comment]
Please also read https://github.com/guardian/frontend/issues/8446 as it has a good description of the problem.

**Comment by michaelwmcnamara** [comment]
Cleanup: All examples cited in this and in https://github.com/guardian/frontend/issues/8446 are now showing credits in lightbox on frontend. Looks like this issue was fixed but the bug was never updated.

**Comment by OliverJAsh** [comment]
We only show the credit and caption iff there is a caption. The caption/credit is not shown for the URLs @paperboyo filed (http://www.theguardian.com/news/2015/apr/09/kremlin-hall-of-mirrors-military-information-psychology, http://www.theguardian.com/commentisfree/picture/2015/feb/26/martin-rowson-on-cover-ups-from-isis-to-nhs-cartoon and http://www.theguardian.com/commentisfree/picture/2015/mar/13/martin-rowson-media-furore-miliband-kitchens-cartoon) because there is no caption. This behaviour is consistent in preview and live.

You were seeing a difference between preview/live because preview had different data to live. This was compouned by a bug in Composer, whereby when you make changes to a caption (specifically on a Picture content type), they are persisted to preview but no option appears to persist the changes to live.

![image](https://cloud.githubusercontent.com/assets/921609/7395707/b3060196-ee93-11e4-8a49-f709e1ef51b6.png)

The orange bar means there are pending changes, but the “Save and launch” button is missing. We should see:

![image](https://cloud.githubusercontent.com/assets/921609/7395720/ca14da9c-ee93-11e4-8c4e-2afa72819387.png)

I have informed the Composer team. /cc @jamespamplin

**Comment by paperboyo** [comment]
Thank you for a comprehensive information, @OliverJAsh!

Two things, if I may, I am a bit dim:

1. I think that while there may be rationale behind not showing all meta while there is no caption for Picture/Cartoon type (because there should be a byline on a page top left, anyway), it’s highly questionable in an example like http://www.theguardian.com/news/2015/apr/09/kremlin-hall-of-mirrors-military-information-psychology. Highly. I am not the author of these illustrations, but I would be pissed off. There are plenty of examples of just the credit showing in the printed paper. Also, how would the reader know the author otherwise? Lastly - there is inconsistency between frontend and Composer here as Composer shows (just credit) meta under these in both body collapsed state and in furniture as ‘Display credit...’... (cc/ @na7angood, also https://github.com/guardian/flexible-content/pull/1551). I understand it’s not a bug, but a concious decision. Just seems to me to be a very wrong one. Who would be the best person to persuade me otherwise, please, because most probably I just haven’t thought about something?

2. http://www.theguardian.com/commentisfree/picture/2015/feb/26/martin-rowson-on-cover-ups-from-isis-to-nhs-cartoon shows the credit in Lightbox; http://www.theguardian.com/commentisfree/picture/2015/mar/13/martin-rowson-media-furore-miliband-kitchens-cartoon doesn’t. Do I understand you correctly that, because of the bug you’ve mentioned, there is currently no way to get them consistent? (I’ve tried editing different fields in both content and furniture and have not succeed).

Thank you again and sorry for the length!

Regards
Mateusz

**Comment by OliverJAsh** [comment]
Agreed. I will follow this up now.

**Comment by paperboyo** [comment]
Forever indebted! :100:

**Comment by OliverJAsh** [comment]
Pushed live, @paperboyo

**Comment by paperboyo** [comment]
Looks good. Big thanks, @OliverJAsh!
