### ISSUE TITLE
IE8 - Gallery Background Text obscured

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#8966]
May be related to issue guardian/frontend#8965 but when you are in a gallery in IE8 due to the background being light in comparison to the usual darker tone colour, the majority of the text is obscured/hard to read. (produced in Windows XP - screenshots with text highlighted and unhighlighted for ease)

![screen shot 2015-04-22 at 11 49 48](https://cloud.githubusercontent.com/assets/11922253/7272804/a1b105fc-e8e5-11e4-905d-d99329eee4ff.png)

![screen shot 2015-04-22 at 11 49 26](https://cloud.githubusercontent.com/assets/11922253/7272792/8e53901a-e8e5-11e4-8d5b-bba9bff2dcaf.png)

**Comment by OliverJAsh** [comment]
This is happening because the html5shiv is broken in IE8 (one of the browsers that needs it the most). I couldn't get to the bottom of the this—the shiv is loaded first and foremost, the but `article{display:block;}` style which is needed to honour the gallery (and footer) background is not being applied, despite the fact it's present on the page.

**Comment by johnduffell** [comment]
since no-one has managed to fix this yet despite trying, it probably won't be fixed soon
