### ISSUE TITLE
All Fronts - Most Popular Container shows most recent content

### ISSUE THREAD

**Issue by ScottPainterGNM** [guardian/frontend#9034]
The most popular container in sport is showing the most recent content rather than most viewed. 

http://www.theguardian.com/uk/sport

(raised by Calvin Dickson via email, I have reproduced)

**Comment by michaelwmcnamara** [comment]
Two things
1)
Currently CAPI are not supporting "most-viewed"in editionalised sections.
I have raised this with them, but until they change this, sections looking to get most viewed results should  change their api call to remove the edition variant - eg /sport... instead of /uk/sport/

2) When you send a request that does result in a "most-viewed" block being populated, we are still displaying the "results" block. We need to change our parsing to display the "most-viewed" block instead.
Suspect these must be recent changes from CAPI.

**Comment by OliverJAsh** [comment]
This was caused by an issue in the content API whereby no "most viewed" data was returned for editionalised sections, e.g. sport or culture, therefore we instead relied on the "most recent" data. This issue has now been fixed.

/uk/sport:

![image](https://cloud.githubusercontent.com/assets/921609/7392074/45667e4c-ee7d-11e4-9614-06c10eaca95d.png)

Ophan most recent for sport:

![image](https://cloud.githubusercontent.com/assets/921609/7392077/49242764-ee7d-11e4-8def-4cd25c85f908.png)
