### ISSUE TITLE
Users reporting comment submission fail message

### ISSUE THREAD

**Issue by JustinPinner** [guardian/frontend#9139]
Users have been reporting seeing error message [when posting new comments]:
`Could not post due to your internet settings, which might be controlled by your provider. Please contact your administrator or disable any proxy servers or VPNs and try again`.

Initially reported by Sian (CP) and userhelp.

**Comment by JustinPinner** [comment]
We're going to explore moving comment submissions away from AJAX CORS calls made from the client to the discussion API. Instead, we'll create a new endpoint within our domain space which will proxy the discussion API call for us.

**Comment by johnduffell** [comment]
this is done

**Comment by Matt2012** [comment]
Still an issue for me

**Comment by johnduffell** [comment]
@Matt2012 this was an issue the whole time, or it was ok for a while and just started happening again in the last couple of weeks?  Are you using IE9?

**Comment by Matt2012** [comment]
Don't know - just happend so I googled and found this.

**Comment by johnduffell** [comment]
Fair enough - what browser are you using Matt?

**Comment by Matt2012** [comment]
Chrome windows could it be adblock?

**Comment by johnduffell** [comment]
I doubt it, we thought it might happen through IE9 because it doesn't support the way we do comment posting to https endpoints.  But it should be fine.  Maybe try another browser see if it's your browser settings or the network connection.

Are you familiar with Chrome Developer Tools?  If so could you take a look at network requests in there (filter by the name "comment") and then try to post a comment.  It should send 2 requests, one OPTIONS and one POST.  Just check they both come back with 200 OK responses.  If you need an old test article to post on try [this one](http://www.theguardian.com/science/grrlscientist/2012/aug/07/3)

**Comment by pssguy** [comment]
I'm getting this for first time
One of many messages on Chrome tools is

 No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.theguardian.com' is therefore not allowed access. The response had HTTP status code 400.

**Comment by jgharston** [comment]
I've  been getting it for months now, but if I went to my profile and looked at Comment Activity eventually the comment showed up so it somehow got through. In the last week or so though it's stopped even doing that.

**Comment by gbjbaanb** [comment]
I have this this morning, using Firefox. The dev tools shows a 503 response from the POST. Maybe the error message could be updated to reflect the 'not available' status instead of the reasonably vague "its probably you" message (when its obviously the server at fault!)

There is a warning in the network trace:

*Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://discussion.theguardian.com/discussion-api/discussion//p/6ahx9/comment/123/reply. (Reason: CORS header 'Access-Control-Allow-Origin' missing).*
