### ISSUE TITLE
Article images should not display camera icons when there is no caption and credits are switched off

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9187]
Hello,

URL: http://www.theguardian.com/film/2015/may/15/son-of-saul-review-an-outstanding-excoriating-look-at-evil-in-auchwitz

The caption field for images in the above is empty and Display credit information is switched off. The camera icon should not be shown:

![camera icon](https://cloud.githubusercontent.com/assets/6032869/7648899/c87e8126-fadf-11e4-9d35-19d3bd3fd1ac.jpg)

Regards
Mateusz

**Comment by paperboyo** [comment]
May or may not be related to a recent - very welcomed - change https://github.com/guardian/frontend/pull/9074...

**Comment by robertberry** [comment]
Turns out there is a caption for each of those images but it's a single space ...

**Comment by paperboyo** [comment]
@robertberry, that’s interesting. I remember checking that before opening the issue. And I’ve double-checked just now. The space is not there as far as Composer UI is concerned (one cannot select the text, nor one can delete it). If it’s in the CAPI, then something would be wrong in Composer... @na7hangood?

**Comment by na7hangood** [comment]
Someone has added a single space for a caption - unnecessarily of course
because we don't require one.
Unchecking the display credit info is unrelated I think because the caption
field isn't linked to the credit fields. More of a training issue than
anything else

On 18 May 2015 at 14:53, Mateusz <notifications@github.com> wrote:

> @robertberry <https://github.com/robertberry>, that’s interesting. I
> remember checking that before opening the issue. And I’ve double-checked
> just now. The space is not there as far as Composer UI is concerned (one
> cannot select the text, nor one can delete it). If it’s in the CAPI, then
> something would be wrong in Composer... @na7hangood
> <https://github.com/na7hangood>?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9187#issuecomment-103067698>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by paperboyo** [comment]
Thanks, @na7hangood. True that about the training, but it’s unrelated. Issue is, that CAPI gives ``"caption": " ",``, but Composer UI does not let you see that there is a space there and, crucially, does not let you delete it. In short - there is no way to correct it now in Composer... :sad_panda:

**Comment by robertberry** [comment]
I think Composer should probably trim that stuff up front. It's true that we can check for it in `frontend` (which I've added a pull request now to do so), but this does mean every client now has to do that, which is nasty. It's much better to be stringent about data validation at the level of creation, rather than have to fix it upstream all the time ...

**Comment by na7hangood** [comment]
I can see them fine in the UI and have deleted them for this url.
True - we could strip in automatically though

On 18 May 2015 at 15:05, Mateusz <notifications@github.com> wrote:

> Thanks, @na7hangood <https://github.com/na7hangood>. True that about the
> training, but it’s unrelated. Issue is, that CAPI gives "caption": " ",,
> but Composer UI does not let you see that there is a space there and,
> crucially, does not let you delete it. In short - there is no way to
> correct it now in Composer... :sad_panda:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/guardian/frontend/issues/9187#issuecomment-103070262>.
>

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396

**Comment by robertberry** [comment]
Yeah, you're never gonna want one of those fields to just be empty space. Should be trivial to do - there's already in-built functions for this in Scala and JavaScript.

**Comment by paperboyo** [comment]
Whoa, @na7hangood! Magic. Then, I suspect a Firefox issue (38.0.5 on Win 8.1), cause I’m not insane, I assure you.

**Comment by paperboyo** [comment]
Yes. Chrome 43, FF 38.0.5 on Win 8.1. In neither can you actually select the single space. In Chrome you can hit Backspace to delete it after focus is in editing field (this does not work in FF, nor does hitting Delete). The only way to delete it in FF is to select all (Ctrl+A) and delete with either Backspace or Delete. That must be one of the smallest issues I found, but at least - I’m not insane. Or...

+1 for them being automatically stripped, closing issue. Thanks, all!
