### ISSUE TITLE
Comments - cant change the order of comments  - the dropdown does not interact

### ISSUE THREAD

**Issue by michaelwmcnamara** [guardian/frontend#9371]
Found on Chrome and firefox for mac but may be common across all browsers.

Order-by comments button is not interactive. I cnat change the order of comment display.
Example  here: http://www.theguardian.com/commentisfree/2015/jun/04/ban-laughing-gas-theresa-may-legal-highs-emotion-not-evidence

![image](https://cloud.githubusercontent.com/assets/7239344/7982656/fd2cc2c6-0ab0-11e5-97c4-3ca2b4f50b5b.png)

**Comment by paperboyo** [comment]
There is a vocal community giving lie to a notion that nobody notices what's going on in here: https://github.com/guardian/frontend/issues/9343, https://github.com/guardian/frontend/issues/9359.

In the process of being fixed in https://github.com/guardian/frontend/pull/9354 by a popular hero @rich-nguyen, I believe... :smile:

**Comment by michaelwmcnamara** [comment]
Excellent - will use https://github.com/guardian/frontend/pull/9354 to track.
