### ISSUE TITLE
Cricket scorecard on over-by-over does not refresh

### ISSUE THREAD

**Issue by adamnfish** [guardian/frontend#9803]
The scorecard at the top of cricket liveblogs is useful, but only if it is up to date!

![cricket-scorecard-stale](https://cloud.githubusercontent.com/assets/29761/8722898/37e7f152-2bc1-11e5-85db-545dacc0d2bb.png)

**Comment by JustinPinner** [comment]
We don't plan to make the scorecard update in real-time yet. Agreed it's a bit naff that the liveblog updates don't agree with the scorecard if you sit and watch the page (or even if you refresh sometimes because the PA feed may be trailing behind a bit), but until liveblog performance issues are eliminated, we won't be adding any additional polling.

**Comment by adamnfish** [comment]
I think the score card should be removed then! It's wrong almost all the time. Given that the updates have the score in the headlines it adds almost nothing to the page except for frustration.

A compromise would be to leave it up for a couple of minutes after page view before removing it (without making any extra calls) so you still get the overview on the initial page load.
