### ISSUE TITLE
Sticky situation replaces site navigation with an advertisment

### ISSUE THREAD

**Issue by paperboyo** [guardian/frontend#9842]
Hello,

There is a considerable period of time - after the main nav disappears and sticky nav shows - when an ad completely replaces site navigation!

![ad replaces nav](https://cloud.githubusercontent.com/assets/6032869/8766134/9afe2bb2-2e23-11e5-9d99-31ded9043cdb.gif)

BTW, I can half-understand why our own Soulmates would be allowed to use Guardian Egyptian fonts. How on earth Cisco is allowed too?! Isn’t our standard (and a good one too) to differentiate advertiser’s content with Guardian Sans?

My strong, if entirely personal, opinion is that we should ditch the whole sticky business. Polishing that on end won’t make it smell any less bad. This is not to belittle anyone’s hard work! One alternative would be to at last introduce a small-payment ad-free membership tier for the site. More money, more performant, lighter site using less battery, an explicit promise of gathering reader’s data _only_ to help serve readers better - a win-win-win situation. Keep it in the ground and less sticky...

Regards
Mateusz

**Comment by OliverJAsh** [comment]
:+1:

For all issues and regressions concerning the sticky nav, see the `sticky-nav` label: https://github.com/guardian/frontend/labels/sticky-nav

**Comment by patstirling** [comment]
Hi Mat - this is as desired; we deliberately do this to maximise the time in view of the ad at the the critical 50% of pixel mark before introducing the sticky nav. On a related note, we've seen engagement increase across the board since launching these changes (can give you the breakdown if you like).

In terms of the font in the ad - in this case it is actually an ad for Guardian content (albeit sponsored by Cisco). As with any sponsored feature, it's entirely editorially independent.

Finally for an ad-free tier - we are exploring that right now.

As ever, please do grab me if you'd like to talk through any of these.

**Comment by paperboyo** [comment]
Hi, Patrick! Thanks for the detailed explanation. Indeed it was "sponsored by" content (http://www.theguardian.com/sponsored-content), entirely my bad, sorry!

I still think that the sticky ad/nav, as currently realised, is problematic for several reasons. Firstly, there are all the bugs/performance issues, especially on mobile. But even after/if we sort out all the bugs there are some design choices I'm not entirely happy with (again, esp. on mobile, sticky nav would better mimic the behaviour of mobile browsers address bars, which are sticky, but do not conceal the content permanently where the screen real estate is so valuable).

Lastly, I do feel that we should try to maximise revenue by possibly not annoying any potential readers ;-) So I'm super-happy to hear about the ad-free tier, also would love to learn about the increased engagement - maybe it's just me who is annoyed and I'm simply wrong? Wouldn't be the first time as well: I happen to think, for example, that there is nothing easier than making money, so that the whole point must be, surely, not to. Or at least not so quickly (like when boiling a frog) :stuck_out_tongue_winking_eye: 

As to this specific issue, while I find it strange that the period where there is no navigation at all is so long, I accept it's a design choice, thus closing. Thx!

**Comment by patstirling** [comment]
Hi Mat,

Good points all - and we making since changes soon to reduce clutter
(including removal of the sticky ad at to of page on mobile - should happen
early next week to be replaced with a simplified mobile advertising
offering, a move which in theory at least will make us more money). We are
also putting lower-powered and "at-risk" devices on a stripped-back version
of the site (which doesn't include sticky nav) to reduce crashes.

In terms of the nav presence - it's worth keeping in mind that just a few
weeks ago there was no nav at all at the point described (it simply slipped
off the screen) - so it's not like something has been taken away.

Engagement-wise, we are seeing increases between 1 and 5% across all
devices and territories; this is higher for certain segments of our
audience. We are undertaking a full review of all numbers this week so can
share more later.

Crucially we

Finally - with you on seeking to improve our revenue generating streams -
we do a lot of things not particularly well, and I wonder if we couldn't
simplify things to do just a couple of them brilliantly.

I wouldn't necessarily say it is the easiest thing in the world to get
right in the media space - we've been losing millions year on year for more
than half a decade now, and just announced a £20M before-tax loss for the
financial year just ended. So any ideas welcome!

Cheers,

Pat

Hi, Patrick! Thanks for the detailed explanation. Indeed it was "sponsored
by" content (http://www.theguardian.com/sponsored-content), entirely my
bad, sorry!

I still think that the sticky ad/nav, as currently realised, is problematic
for several reasons. Firstly, there are all the bugs/performance issues,
especially on mobile. But even after/if we sort out all the bugs there are
some design choices I'm not entirely happy with (again, esp. on mobile,
sticky nav would better mimic the behaviour of mobile browsers address
bars, which are sticky, but do not conceal the content permanently where
the screen real estate is so valuable).

Lastly, I do feel that we should try to maximise revenue by possibly not
annoying any potential readers ;-) So I'm super-happy to hear about the
ad-free tier, also would love to learn about the increased engagement -
maybe it's just me who is annoyed and I'm simply wrong? Wouldn't be the
first time as well: I happen to think, for example, that there is nothing
easier than making money, so that the whole point must be, surely, not to.
Or at least not so quickly (like when boiling a frog) [image:
:stuck_out_tongue_winking_eye:]

As to this specific issue, while I find it strange that the period where
there is no navigation at all is so long, I accept it's a design choice,
thus closing. Thx!

—
Reply to this email directly or view it on GitHub
<https://github.com/guardian/frontend/issues/9842#issuecomment-127340826>.

-- 

------------------------------
Visit theguardian.com. On your mobile and tablet, download the Guardian 
iPhone and Android apps theguardian.com/guardianapp and our tablet editions 
theguardian.com/editions.  Save up to 57% by subscribing to the Guardian 
and Observer - choose the papers you want and get full digital access. 
 Visit subscribe.theguardian.com

This e-mail and all attachments are confidential and may also be 
privileged. If you are not the named recipient, please notify the sender 
and delete the e-mail and all attachments immediately. Do not disclose the 
contents to another person. You may not use the information for any 
purpose, or store, or copy, it in any way.  Guardian News & Media Limited 
is not liable for any computer viruses or other material transmitted with 
or as part of this e-mail. You should employ virus checking software.
 
Guardian News & Media Limited is a member of Guardian Media Group plc. Registered 
Office: PO Box 68164, Kings Place, 90 York Way, London, N1P 2AP.  Registered 
in England Number 908396
