### ISSUE TITLE
Discussion Abuse Reports: put through theguardian.com proxy

### ISSUE THREAD

**Issue by gidsg** [guardian/frontend#9897]
We have had some reports from legal of abuse reports not being received.
I believe this could be because abuse reports are not currently put through the same domain proxy like Comments so may fail due to lack of CORS support.

Steps to reproduce
===============
Go to: http://www.theguardian.com/science/grrlscientist/2012/aug/07/3
Open Developer Console
Report Abuse on a comment

Actual Results
===========
Posts to: `http://discussion.guardianapis.com/discussion-api/comment/56132192/reportAbuse`

Expected Results
==============
Posts to `http://www.theguardian.com/guardianapis/discussion/discussion-api/comment/56132192/reportAbuse`

CC @guardian/discussion @JustinPinner @OliverJAsh

**Comment by OliverJAsh** [comment]
> I believe this could be because abuse reports are not currently put through the same domain proxy like Comments so may fail due to lack of CORS support.

Which browsers are you referring to here? IE8+ have CORS support, albeit using an alternative technique.

**Comment by gidsg** [comment]
> Which browsers are you referring to here?

Not browsers, but users going through HTTP 1.0 Proxies which do not support CORS. Please see https://github.com/guardian/frontend/pull/9560 or talk to @johnduffell for more info on this.

**Comment by OliverJAsh** [comment]
@gidsg It seems like we should be doing this for all requests, or not at all?

**Comment by gidsg** [comment]
Well, yes, I see your point, there is obviously no benefit for GETs but I could enable it for all POSTs in #9916?

**Comment by OliverJAsh** [comment]
Can you remind me of the problem? I understand some users may be behind a HTTP 1 proxy. CORS works for GET but not for POST. Why is this? @johnduffell @gidsg

**Comment by johnduffell** [comment]
cors is basically an extra header from the target server to tell the browser it's ok to use the info from the cross domain request rather than in the past the browser just refusing completely.  If the server doen't support cors the header isn't there so everything will be disallowed - safe.
However this doesn't make sense for POST because the data is sent already to the server and the server would act on it if the server didn't support cors.  That would be a bad thing.  So the OPTIONS has to happen first, then if the server doesn't support CORS the browser finds out about it and never sends the POST thus preventing the risk.
However HTTP1.0 doesn't have OPTIONS so the proxy throws a fit when it sees it.  However proxies are supposed to pass through unknown headers on a GET so it doesn't get in the way of that.

**Comment by OliverJAsh** [comment]
Ah, of course, because the preflight `OPTIONS` is not supported.
