### ISSUE TITLE
frontend.properties sample

### ISSUE THREAD

**Issue by fnouama** [guardian/frontend#9923]
Hello guys,

I think that you should provide a template of this properties file. It will be helpful to figure the entire set of properties to configure.

thanks

**Comment by OliverJAsh** [comment]
Seems like a fair request. Could we provide a template along with instructions for how to produce the necessary API keys?

**Comment by fnouama** [comment]
Thank you @OliverJAsh

**Comment by rich-nguyen** [comment]
The repo is of course available for you to clone and develop with, however we don't provide any support for developing/running the codebase independently. The only reason for this is that we haven't got enough resources to provide that kind of support, as much as I personally would like to.

My fear is that I could happily give you a template properties file, but, since it's a template, this would only cause more errors to debug and diagnose.

That said, the expected contents of the properties file can be read from [configuration.scala](https://github.com/guardian/frontend/blob/master/common/app/common/configuration.scala), and the log reports any missing configuration. Hope that helps.
